baseURL = "https://juanmagdaraog.com/gcf/"
languageCode = "en-us"
title = "ADB and the GCF"
summaryLength = 10

# Site Menus
[menu]
# Navbar Menus
 [[menu.main]]
   identifier = "home"
   name = "Home"
   url = "/"
   weight  = 1

[[menu.main]]
  identifier = "adb-and-the-gcf"
  name = "ADB and the GCF"
  url = "/adb-and-the-gcf/"
  weight  = 2

[[menu.main]]
  identifier = "partnership-at-a-glance"
  name = "Partnership at a Glance"
  url = "/partnership-at-a-glance/"
  weight  = 3

[[menu.main]]
  identifier = "our-projects"
  name = "Our Projects"
  url = "/our-projects/"
  weight  = 4


[markup]
[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
